### ISSUE TITLE
BALANCE - New Homepage 

### ISSUE THREAD

**Issue by Majed610** [Aliado-Leipzig/VNG#1]
Hi guys, 

we have a go for the project.  
Old website; https://www.balance-vng.de
The final Design: https://xd.adobe.com/view/6b95e56f-4cba-4bbc-b6e8-2f1f94acefa1-3ec6/specs/ 
Design assets: [BALANCE_Web_Elemente.zip](https://github.com/Aliado-Leipzig/VNG/files/7960372/BALANCE_Web_Elemente.zip)
Below you find a list of the detailed tasks in case there is something not really clear in the XD-file. The designers tried to do a good job by adding all the elements of the design template into XD and you find them also attached to this issue. 

Tasks for homepage: 

- [ ] Editing the template in the test backend in order to adapt the new changes: 
New template settings:  
> Content width: 1920px 
> Hero (header) width: full width  
> Header element: image slider  (XD slides: 1-3 shows the variables); automatic slider with 3-5 sec. transition
> Header title: Text & CTA button 
> Dotted circles should be implemented on the main template except homepage (slides are included already with dots)
/graphic is for download in the xd/

- [ ] Sticky Contact Button on right side of screen
(Same as the actual one on the website just different design) 

- [ ] Footer on Homepage 
Footer background only on Homepage with gradient (details in XD) 

If you have any questions, please don't hesitate to contact me!

**Comment by Majed610** [comment]
@WifredoMedanoSolution 

The needed graphics: 
![BALANCE_Web_Pfeil_weiss](https://user-images.githubusercontent.com/89200332/152386962-e4e8eafc-f320-4d93-bb4b-26042b7f3105.svg)
![BALANCE_Web_Pfeil_gruen](https://user-images.githubusercontent.com/89200332/152386963-0f471676-8944-4fb0-a930-8678afdeef80.svg)

hope those are the correct ones. If you need another version please let me know.

**Comment by WifredoMedanoSolution** [comment]
Hello Majed,
thank you very much for the image, it's fine. Sorry for the delay in replying, but we are very busy. This week has been one of the hardest since I've been working here.

The homepage design is almost ready, although there are still some details to finish. We hope to have everything ready really soon.

We might have a call next week, discuss the current progress and any questions we have. What do you think? I leave the choice of schedule up to you.

Regards
Wifredo

**Comment by WifredoMedanoSolution** [comment]
Hi again Majed,
In this page you can take a look to the Product page so far: https://bal.vng.aliado.rocks/produkte/

Have a nice weekend,
Wifredo

**Comment by Majed610** [comment]
Hi @WifredoMedanoSolution, 

thanks for the update. 

Yeah perfect. Let's have a call on Monday 4 pm or Tuesday 2 pm. Choose which suits you best and we can discuss the details and clear any questions. 

have a nice weekend and till next week,
Majed

**Comment by WifredoMedanoSolution** [comment]
Hello Majed,
we can have the meeting tomorrow Tuesday at 2pm (1pm Canary Islands time)

Best regards
Wifredo

**Comment by Majed610** [comment]
Hi Wifredo,

Great. I will set-up a Teams meeting.

Best regards and a good start in the week,
Majed

Von: WifredoMedanoSolution ***@***.***>
Gesendet: Montag, 7. Februar 2022 09:39
An: Aliado-Leipzig/VNG ***@***.***>
Cc: Majed Mustafa ***@***.***>; Author ***@***.***>
Betreff: Re: [Aliado-Leipzig/VNG] BALANCE - New Homepage (Issue #1)


Hello Majed,
we can have the meeting tomorrow Tuesday at 2pm (1pm Canary Islands time)

Best regards
Wifredo
