### ISSUE TITLE
Feedback Update 24.04.2022

### ISSUE THREAD

**Issue by Majed610** [Aliado-Leipzig/VNG#16]
Hi Adrian, 

today i received a new Feedback from client regarding some points: Please check and estimate time individually:

- [x] Change Logo to this one:
![logo 4c zw ohne VNG Stiftung](https://user-images.githubusercontent.com/89200332/165071130-5af1609d-90d7-461f-9342-cc465b1cd7f1.svg)

- [x] Please change CSS-Classes kontakt-label & kontakt-label-hidden to 20px 

- [x] ![image](https://user-images.githubusercontent.com/89200332/165072435-15e454e7-d45a-4291-a4c5-297b00ef13db.png)

- [x]  replace logo of stiftung im footer with this one
![VNG Stiftung LOGO CMYK 5 Bereiche 1c weisser Schriftzug](https://user-images.githubusercontent.com/89200332/165072641-d7650597-9a79-4c44-9381-6561e94a5894.svg)

- [x] Diclaimer, Impressum, Datenschutz have different typography settings. H3 is not the same everywhere.
- [ ] How easy is it possible to show and hide the contact row with social Media on top.
- [x] The filter in aktuelles is missing, did you insert a category or date search option? 
- [x] The cookie banner is still missing on the website. We have to adopt the one from VNG Stiftung
- [x] On mobile: Aktuelles: The subheading: " Wir informieren Sie über..." is not Officina. Please correct. 

Kontakt-form:
I noticed an error with the contact form. Everytime when i try to fill a form. The entry field moves up and removes the description of the field.
![image](https://user-images.githubusercontent.com/89200332/165085832-48fe2fe1-5d8d-4d55-99e8-8ca1eacd4805.png)

- [x] Please check and correct.

**Comment by Mirsho** [comment]
Hello Majed,

I checked the feedback update and have some comments and questions. I'll divide it into tasks that are updates/fixes and tasks that are new changes (extra time).

### **Updates/Fixes:**

- "How easy is it possible to show and hide the contact row with social Media on top."

The contact + social media top row is currently commented on the header template. It just needs to be uncommented and updated via FTP.

Another option is to build a wp backend setting to show or hide that row (extra time: +1 hour).

- "The filter in aktuelles is missing, did you insert a category or date search option?"

The aktuelles category filter was disabled while the editors were adding news after the live launch. I enabled it on the Testsystem for you to check it. The filter is from the WP Bakery grid element and is displayed natively as a category row to achive a better performance, but I can style as the design draft.

https://vdw.vng.aliado.rocks/aktuelles/

For the project filter, we can add categories to the project entries and place the same filter. If the client wants a date filter I can add a custom code to have it.

- The Kontact-form error came from the form plugin, it's changing the input styles when filled. I can quickly fix it.


### **New changes (extra time):**

- What do you mean about the main footer section image with the blue separation arrows?

- "Diclaimer, Impressum, Datenschutz have different typography settings. H3 is not the same everywhere."

The styles are the same for every h3.

Impressum page doesn't have any h3 element apart from the one on the mobile footer slide-up (common for all pages).

The Disclaimer and Datenschutz pages have the same h3 styles, but on the Disclaimer page, the VNG editors wrote the titles in lowercase while writing them uppercase with a font-weight: 400 on the Datenschutz page.

- "The cookie banner is still missing on the website. We have to adopt the one from VNG Stiftung"

The cookie banner is currently hidden on the VdW build. It has the JS code and styles from Stiftunh as it was originally a clone of it. I need the design draft for the banner to style it and enable, it wasn't present on the design drafts.

- "On mobile: Aktuelles: The subheading: " Wir informieren Sie über..." is not Officina. Please correct."

What do you mean? Currently te subheading is "Wir informieren Sie hier über unsere Arbeit."

- Header logo, footer logo and CSS change

Extra time estimation: 3.5 hours (+1 if wanted the contact/social media banner setting)
