### ISSUE TITLE
Layout Updates 07.03.2022

### ISSUE THREAD

**Issue by Majed610** [Aliado-Leipzig/VNG#7]
Hi guys,

thanks for the updates from last week. Here are the remaining points i got from the client:

**Jobs:** 
- [x] Change Jobs to "Karriere" in the navigation
- [x] Please calculate estimated time for adding a contact person to the job page https://xd.adobe.com/view/8b4a0463-2872-440a-80f9-14b254ce0fdf-de19/screen/ecb4f0db-2bcf-4fa3-85c1-be599035c394
![image](https://user-images.githubusercontent.com/89200332/157036766-15758359-c8ee-4847-93c6-7d08aa4a9f5a.png)

Website width:
- [x] padding for width between 1190 - 1780px
- [x] solve vertical scrolling of the website
- [x] reduce all H1 & H2 around 20%

Homepage: 
- [x] on mobile: over the product section, there is a dotted graphic, please remove
- [x] Change Slide 1 with video of "about us" and put the image of slide 1 in the about us page

- [x] remove cookie banner from the website

**Comment by Majed610** [comment]
Hi Adrian, 

great thanks but the website looks a little odd for me now: 
![image](https://user-images.githubusercontent.com/89200332/157060782-717b5add-02b0-479a-92bf-bdccfaa2273d.png)

i have another thing for responsive bug on the about us page: 

- [ ] Please align the text with the heading, because in some sections it is moved slightly to the right.

![image](https://user-images.githubusercontent.com/89200332/157060890-97dc01e4-f15c-412a-95de-80c51c5bb311.png)

- The slide in the about us page is fine like this but the crescent at the end of the about us page is still pixelated. 
-  The contact person we can do as after Go Live

Before you start migrating please give me a message  on telegram so i have the final go from the client. 

Thanks a lot

**Comment by Mirsho** [comment]
Thanks for the review!

The text alignment on the Über uns mobile is ready.

Can you please check again the video on the slider after clearing cache? (or refreshing with ctrl+F5)

For the footer crescent, I need the SVG file.

![Footer-Background](https://user-images.githubusercontent.com/50135963/157068717-08ae3a3f-9cd5-4702-bed1-b1cc3f760fa8.png)

I only have this png and can't take the asset alone from the Adobe XD.

The width + scrolling fix is being tricky, If you agree, I can finish it after the migration, along with the contact person and the needed corrections.

In that case, please ask for the final go from the client.

Thank you!

**Comment by Majed610** [comment]
![BALANCE_Footer_Rundung_Beige](https://user-images.githubusercontent.com/89200332/157082290-df2d192d-37d4-4492-8ae2-c626468f9a81.svg)

here the svg file for crescent

**Comment by Majed610** [comment]
New Updates on LIVE: 

Slider:

- [ ] Brake the text on top of the video after "Menschen"  so it looks like this:

"Wir versorgen Menschen
mit gesunder Energie" 

Mobile-Menü:
- [ ]  active link on mobile should be like on desktop, medium green and not yellow

Pages: 

- [ ] the animated dots on scroll should all have the same size like on the products. 
- [ ] please check that the dots and the graphic is not cut and that it's a full circle
![image](https://user-images.githubusercontent.com/89200332/157198483-8a9319b8-6638-4131-b52a-f651423c945b.png)


About us:

- [ ] Please change the mobile image for the "leitbild" section into this image 
![BALANCE_UeberUns_LeitbildMobil](https://user-images.githubusercontent.com/89200332/157198744-0f65d4f8-1055-467f-a3e8-40abb3daf359.jpg)

- [ ] PLease change the about us header into this image
![BALANCE_UeberUns_HeaderNeu](https://user-images.githubusercontent.com/89200332/157198821-9000d701-b306-45a6-a450-c1be443991c5.jpg)

**Comment by Majed610** [comment]
The Crescent is still not showing on the web, you might have to change the url from the testsystem, because i see it when my htaccess is active
![image](https://user-images.githubusercontent.com/89200332/157205486-5c6fcc81-7cdf-473b-8446-ab0e051eca4f.png)

**Comment by Majed610** [comment]
@Mirsho 
i Still have following problems on responsive:

- [ ] Slider is showing a black piece of the video on the bottom
- [ ] dots are too big and not in the middle of the screen
- [ ] the buttons under the text are too big, please change to the size of the regular responsive buttons 
![image](https://user-images.githubusercontent.com/89200332/157214458-229b6e67-b498-4f4e-a045-90cbd5568eab.png)

- [ ] the website scrolls on mobile left & right
- [ ] on the map page: the footer is showing a white section at the end 
![image](https://user-images.githubusercontent.com/89200332/157214339-a864db56-e02f-4e2b-b26f-dc1a614df425.png)

**Comment by Mirsho** [comment]
Thanks for the annotations. I'm fitting everything carefully on the live system.

Pending tasks summary:

Website width:

- [ ] padding for width between 1190 - 1780px
- [ ] solve vertical scrolling of the website

Karriere:

- [ ] contact person image

About us:

- [ ] change the mobile image for the "leitbild" section

Responsive:

- [ ]  dots are too big and not in the middle of the screen
- [ ]  the buttons under the text are too big, please change to the size of the regular responsive buttons
- [ ]  the website scrolls on mobile left & right (related with website width
- [ ] Check slider in tablet breakpoints

Other

- [ ]  on the map page: the footer is showing a white section at the end (check footer.php)
